### ISSUE TITLE
    - The requested package pheme/yii2-jui-timepicker could not be found in any version, there may be a typo in the package name.

### ISSUE THREAD

**Issue by pptyasar** [phemellc/yii2-jui-timepicker#1]
Problem 1
    - The requested package pheme/yii2-jui-timepicker could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by arisk** [comment]
Hi,
Can you try again?

**Comment by pptyasar** [comment]
Now its worked
